language:
  python

sudo:
  false

virtualenv:
  system_site_packages:
    false
  
env:
  matrix:
    # Python 2, oldest supported packages
    - DISTRIB="conda" PYTHON="2.7" PACKAGES="oldest" DEPS="true"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="false"

    # Python 2
    - DISTRIB="conda" PYTHON="2.7" PACKAGES="current" DEPS="true"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="false"

    # Python 3
    - DISTRIB="conda" PYTHON="3.5" PACKAGES="current" DEPS="true"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="true"

    # environment without optional dependencies
    - DISTRIB="conda" PYTHON="3.5" PACKAGES="current" DEPS="false"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="true"
      
install:
  source distributions/ci/install.sh

script:
  source distributions/ci/run_tests.sh

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then codecov; fi
